### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by jaimevillegas** [dicodiaz/recipe-app#11]
Hi there!

@dicodiaz and I have worked on setup the Kanban board according to the project requirements.

Link of the Kanban project:
https://github.com/users/dicodiaz/projects/3

Thank you so much for taking the time to review our project! ⚡

**Comment by julie-ify** [comment]
Hi @jaimevillegas and @dicodiaz,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* Kindly note that you should include the link to the Kanban board in the issue.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jaimevillegas** [comment]
Hello @julie-ify 

Thank you for your comment! We have now added the link to the issue

**Comment by julie-ify** [comment]
## Hi @jaimevillegas and @dicodiaz,

Good job so far!

## Highlights!
- Descriptive tasks ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [x] Kindly add a task for this requirement.

  ![image](https://github.com/dicodiaz/recipe-app/assets/81468675/f969fe76-dda6-43c7-b8ae-cae1de4fc14f)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jaimevillegas** [comment]
Hello @julie-ify 

Thank you for your comment. @dicodiaz and I have added and assigned that task!

**Comment by julie-ify** [comment]
Hi @jaimevillegas and @dicodiaz,

## Highlights!
- Descriptive tasks ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
